// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjHk1UL5QZCAhkiIiFvQP3AfPDEm2Evic',
    appId: '1:70421291826:web:c97ffbd70264c191d72d2b',
    messagingSenderId: '70421291826',
    projectId: 'fir-seventhsem',
    authDomain: 'fir-seventhsem.firebaseapp.com',
    storageBucket: 'fir-seventhsem.appspot.com',
    measurementId: 'G-Z632V3BZMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-q2-XFVH3n3Ss7qg9XHpdIJNtbP32trc',
    appId: '1:70421291826:android:4d696d88133185fbd72d2b',
    messagingSenderId: '70421291826',
    projectId: 'fir-seventhsem',
    storageBucket: 'fir-seventhsem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIGJ_2afeOGyfQv1j8vd3KkUq9b23Gdvk',
    appId: '1:70421291826:ios:3bc9f594e640000dd72d2b',
    messagingSenderId: '70421291826',
    projectId: 'fir-seventhsem',
    storageBucket: 'fir-seventhsem.appspot.com',
    iosBundleId: 'com.example.seventhSemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIGJ_2afeOGyfQv1j8vd3KkUq9b23Gdvk',
    appId: '1:70421291826:ios:582a24eb4898e20dd72d2b',
    messagingSenderId: '70421291826',
    projectId: 'fir-seventhsem',
    storageBucket: 'fir-seventhsem.appspot.com',
    iosBundleId: 'com.example.seventhSemProject.RunnerTests',
  );
}
